;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;                      This is the botman conf
;
;==========================================================

[colors]
background = #131329
foreground = #131329
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

i3 = #535773
i3_unfo = #3E4156
clock = #6F83BF
network = #ADC5D9
sound = #F2DFBB
fs = #A6705D
logo = #535773

[bar/example]
monitor = ${env:MONITOR:} 
width = 98.3%
height = 30 
radius = 10.0
fixed-center = true

override-redirect = true

offset-x = 0.95%
offset-y = 8

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 10
line-color = #000000

border-size = 7
border-color = ${colors.background}

# module-margin-left = 2
# module-margin-right = 2

font-0 = AgaveNerdFont:pixelsize=13:wheight=bold;2
font-1 = AgaveNerdFont:pixelsize=26:wheight=bold;5
font-2 = AgaveNerdFont:pixelsize=15:wheight=bold;2

modules-right = leftn wifi ethernet rightn lefta audio righta leftf filesystem rightf
modules-center = leftc clock rightc
modules-left = logo lefti i3 righti

scroll-up = "#i3.prev"
scroll-down = "#i3.next"

tray-position = none 

wm-restack = i3

cursor-click = pointer
cursor-scroll = ns-resize

[module/temperature]
type = internal/temperature

interval = 0.5
hwmon-path = /sys/devices/virtual/thermal/thermal_zone0/hwmon3/temp1_input
base-temperature = 30
warn-temperature = 75

label = CPU %temperature-c%
label-foreground = colors.foreground 
label-background = #994B56 
label-padding = 15px

label-warn = TEMP %temperature-c%
label-warn-foreground = #f00

width = 5%

[module/wifi]
type=internal/network
interface = wlan0
interface-type = wireless 

format-connected = <ramp-signal> <label-connected>
label-connected = "%essid% | 󱚶 %downspeed% | 󱚺 %upspeed%"

ramp-signal-0 = 󰤮
ramp-signal-1 = 󰤯
ramp-signal-2 = 󰤟
ramp-signal-3 = 󰤢
ramp-signal-4 = 󰤥
ramp-signal-5 = 󰤨

animation-packetloss-0 = ⚠
animation-packetloss-0-foreground = #ffa64c
animation-packetloss-1 = 📶
animation-packetloss-1-foreground = #000000

animation-packetloss-framerate = 500

width = 10%
format-connected-background = ${colors.network}
color = ${colors.network}

[module/ethernet]
type=internal/network
interface = eno1
interface-type = wired

format-connected = <label-connected>
label-connected = "󰈀 %local_ip% |   %downspeed% |   %upspeed%"

animation-packetloss-0 = ⚠
animation-packetloss-0-foreground = #ffa64c
animation-packetloss-1 = 📶
animation-packetloss-1-foreground = #000000

animation-packetloss-framerate = 500

width = 10%
format-connected-background = ${colors.network}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
mount-1 = /mnt/disk1
mount-2 = /mnt/disk2
mount-3 = /mnt/disk3

label-mounted =   %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}
spacing = 0

width = 10%
format-mounted-background = ${colors.fs}
format-mounted-padding = 20px

[module/i3]
type=internal/i3

pin-workspaces = true
strip-wsnumbers = true
index-sort = true
fuzzy-match = true

format = %{T3}<label-state> <label-mode>%{T-}

ws-icon-0 = 1:Terminal;
ws-icon-1 = 2:Firefox;󰈹
ws-icon-2 = 3:Obsidian;󱞁
ws-icon-3 = 4:Discord;󰙯
ws-icon-4 = 5:KeePassXC;
ws-icon-5 = 6:OBS;
ws-icon-default = 

label-mode = %mode%
label-mode-background = #535773

label-focused = %icon%  %name%
label-focused-foreground = ${colors.foreground} 
label-focused-background = ${colors.i3} 
label-focused-padding = 1

label-unfocused = %icon% 
label-unfocused-padding-right = 2 
label-unfocused-padding-left = 1.4
label-unfocused-background = ${colors.i3_unfo}
label-unfocused-foreground = ${colors.foreground}

label-visible = %icon%
label-visible-padding-right = 2
label-visible-padding-left = 1.4
label-visible-background = ${colors.i3_unfo}
label-visible-foreground = ${colors.foreground}

label-separator = |
label-separator-background = ${colors.i3_unfo} 
label-separator-foreground = ${colors.foreground}

label-urgent = %index%: %icon%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-padding = 4 

[module/clock]
type=internal/date

date = %d-%m-%Y
time = %H:%M

date-alt = %A, %d %B %Y
time-alt = %H:%M:%S

format = <label>
format-background = ${colors.clock}
format-foreground = ${colors.foreground}
format-padding = 20px

label = %date% %time%
label-foreground = ${colors.foreground} 

[module/audio]
type = internal/pulseaudio

use-ui-max = false 

format-volume-padding = 1
format-volume = <ramp-volume> <label-volume>

label-volume = %percentage:4%% 
format-volume-foreground = ${colors.foreground}
format-volume-background = ${colors.sound} 

format-muted = <label-muted>

label-muted = 󰸈 muted
label-muted-padding = 1
label-muted-foreground = ${colors.foreground}
label-muted-background = ${colors.sound}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/logo]
type = custom/text

content = 󰣇 
content-background = ${colors.background}
content-foreground = ${colors.logo}
content-padding = 1
content-font = 2

click-left = rofi -show power-menu -modi power-menu:$HOME/.local/bin/rofi-power-menu

# ROUND border
[module/righti]
type = custom/text
content = %{T2} %{T-}
content-foreground = ${colors.i3_unfo}

[module/lefti]
type = custom/text
content = %{T2} %{T-}
content-foreground = ${colors.i3_unfo}

[module/rightc]
type = custom/text
content = %{T2} %{T-}
content-foreground = ${colors.clock}

[module/leftc]
type = custom/text
content = %{T2} %{T-}
content-foreground = ${colors.clock}

[module/rightn]
type = custom/text
content = %{T2} %{T-}
content-foreground = ${colors.network}

[module/leftn]
type = custom/text
content = %{T2} %{T-}
content-foreground = ${colors.network}

[module/righta]
type = custom/text
content = %{T2} %{T-}
content-foreground = ${colors.sound}

[module/lefta]
type = custom/text
content = %{T2} %{T-}
content-foreground = ${colors.sound}

[module/rightf]
type = custom/text
content = %{T2} %{T-}
content-foreground = ${colors.fs}

[module/leftf]
type = custom/text
content = %{T2} %{T-}
content-foreground = ${colors.fs}

[settings]
screenchange-reload = true
content-foreground = ${colors.clock}

[global/wm]
margin-top = 10
margin-bottom = 0
